# Site settings
title: in sapientia ambulate tempus redimentes
header-img: img/home-bg.png
email: vernapii@gmail.com
copyright_name: jojojoleeleelee
description: > # this means to ignore newlines until "baseurl:"
  On learning new languages
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jojojoleeleelee
learn_profile: jojojoleeleelee
email_username: vernapii@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
